version: "3.8"
services:
  server:
    build: ./server
    container_name: server_container
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mysql_db
  mysql_db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABSE=api
      - MYSQL_ROOT_USER=root-user
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=127.0.0.1
